language = "C++"
namespace = "pchip_ffi"

[export]
include = [
    "PchipSlopesResultFfi",
    "PchipInterpolatorFfi",
    "ReverseInterpolateResult",
    "PchipInterpolatorResultFfi",
    "GainCurveFfi",
    "GainCurveResultFfi",
]
